title: Blue Core Project
description: The Blue Core Project envisions a new library metadata environment with linked data at its core that is cooperatively shaped and owned, eliminating the need for every institution to establish linked data tooling locally.

markdown: kramdown
